plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - 20220516-Whitebit.-Gde-dengi,-Lebovski.md
  - 20220519-Pokupki-paketov-po-margo6.md
  - Game.-Registraciya-po-referalno–π-ssylke.md
